### ISSUE TITLE
Episode 2

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#3]
Some ideas for possible changes/edits related to [episode 2](https://umn-dash.github.io/r-shiny/shiny_2.html). This is a bit long, but they're all pretty minor points! Episode went pretty smoothly for me.

- [x] You might remove the [install directions in the setup](https://umn-dash.github.io/r-shiny/index.html#required-setup) and leave [them in episode 2.](https://umn-dash.github.io/r-shiny/shiny_2.html#installing-packages) Repetitive to have them in both places. 
- [x] In step 4 when [creating a new project](https://umn-dash.github.io/r-shiny/shiny_2.html#establishing-our-shiny-apps-project-folder), it might be easier to have everyone call their project directory the same thing -  _shiny_workshop_, or something like that. That way it would be easier for instructors to refer back to the directory throughout.
- [x] It feels odd to have learners create the `inputs/` and `Rcode/` directories, since you mention they won't use them during the workshop. You could keep those bullet points and describe their utility, but not have students create them. OR you could be explicit about why they're creating those even though they won't use them (e.g., it could be helpful to leave the workshop with a well-structured project).
- [ ]~~If you want to make cuts for time, I think you could reduce the intro to [mobile design](https://umn-dash.github.io/r-shiny/shiny_2.html#jumpstarting-our-ui), especially since you describe the specifics when implementing fluid rows, etc.  But it felt a bit off-topic for me.~~
- [x] From the screenshots and text when you run your app, it seems like it previews in the browser. But mine opens a little R box to preview. I have to choose "Open in Browser" to preview it there. I'd be explicit about launching that so everyone is on the same page.

**Comment by BajczA475** [comment]
I massaged the wording in the Setup for item 1 here to indicate that it was optional, though a nice bonus, to install them up front. I worry too few people will actually read the setup instructions and will run into errors without the reminder to install the packages in Episode 2. I did also shorten this bit in Episode 2 as well though. I was also worried that installing during the lesson might take a while, since we do use quite a few packages....

**Comment by BajczA475** [comment]
item 2 is done--I use the suggestion given, though I still phrase it as somewhat optional since I don't personally refer back to the root directory much if ever, but I recognize others might, so I see the utility!

**Comment by BajczA475** [comment]
For Item 3 here, I decided to make these optional bits more explicitly optional and also to put them in a callout so they are visually distinct from the rest of the content in this section. I like highlighting them still, as I feel they are part of my "default kit" for an app, but it's true I don't use them here and thus we should marginalize them a bit.

**Comment by BajczA475** [comment]
I appreciate the suggestion here for Item 4, but I think the mobile-first design piece here is essential, and I highlight it more in the in-person material because it motivates how we lay out the app. I also think it's the easiest such paradigm to explain to beginners and a good starting point. Maybe the bit here needs editing to be less verbose, but I think it's too key to my goals to cut entirely.

**Comment by BajczA475** [comment]
Item 5 here is a good catch and a big oversight--launching in the browser is THE way to go here for sure, but I forget it isn't the default way! I made this area in the script a callout and added a note to switch to launching externally here.
