### ISSUE TITLE
episode 4: full code for ui.R and server.R 

### ISSUE THREAD

**Issue by chennesy** [umn-dash/r-shiny#6]
It would be helpful to provide the full code for the ui.R and server.R files from [episode 3](https://umn-dash.github.io/r-shiny/shiny_3.html) at the beginning of [episode 4](https://umn-dash.github.io/r-shiny/shiny_4.html). It's easy to make small mistakes when adding the code throughout - especially if you inadvertently delete a curly bracket or parenthesis, or put stuff in the wrong order in ui.R. So it would be helpful for self-paced learners to have a couple of reference files they can use to start fresh for episode 4.

**Comment by BajczA475** [comment]
@chennesy Good call. Next push will contain a "Catching up" section at the outset of the 4th lesson. Can you confirm that the three code blocks contain the right content and that it functions? I don't have "running snapshots" of the code because it's so iterative, so I tried to recreate it from memory using the final app code...

**Comment by chennesy** [comment]
@BajczA475 The starter code at the beginning of episode 4 works for me, and the app seems to be right in line with where we left off in episode 3. thanks!

**Comment by BajczA475** [comment]
(Whew!) Thanks for checking!
